theme: jekyll-theme-modernist
title: Lars Eivind Lien
description: I am a 4.year student, studying Engineering and ICT at NTNU, Trondheim. 
description: Here, I will post different projects I have worked with during my time as a student.
